[package]
name = "utoipauto"
version = "0.4.0"
edition = "2021"
authors = ["RxDiscovery", "ProbablyClem"]
rust-version = "1.69"
keywords = ["utoipa", "openapi", "swagger", "path", "auto"]
description = "Rust Macros to automate the addition of Paths/Schemas to Utoipa crate, simulating Reflection during the compilation phase"
categories = [
    "parsing",
    "development-tools::procedural-macro-helpers",
    "web-programming",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rxdiscovery/utoipauto"
homepage = "https://github.com/rxdiscovery/utoipauto"
[lib]


[dependencies]
utoipa-auto-macro = { version = "0.4.0", path = "./utoipa-auto-macro" }


[dev-dependencies]
utoipa = { version = "4.1.0", features = ["preserve_path_order"] }
syn = { version = "2.0.39", features = ["extra-traits", "full"] }
