name: ci

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: none

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ "1.74.0", "stable", "nightly" ]
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@master # Needed to always have access to the latest releases. DO NOT REPLACE WITH STABLE!
        with:
          toolchain: ${{ matrix.rust }}
        env:
          RUSTUP_TOOLCHAIN: ${{ matrix.rust }}
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with all features
        run: cargo test --all-features --verbose

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: run formater
        run: cargo fmt --check

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: run formater
        run: cargo clippy -- -D warnings
