name: ci

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with all features
        run: cargo test --all-features --verbose
      - name: Run utoipauto-core tests
        run: cargo test --manifest-path utoipauto-core/Cargo.toml --verbose --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: run formater
        run: cargo fmt --check

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: add cargo caching
        uses: Swatinem/rust-cache@v2
      - name: run formater
        run: cargo clippy -- -D warnings
